AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 pública con Amazon Linux, usando AMI por región mediante Mappings

Parameters:
  StackNamePrefix:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  InstanceProfile:
    Type: String

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0f88e80871fd81e91
    us-west-2:
      AMI: ami-0892d3c7ee96c0bf7
    eu-west-1:
      AMI: ami-05f7491af5eef733a

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", AMI ]
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: !Sub '${StackNamePrefix}-EC2'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Bienvenido al laboratorio CloudFormation Free Tier</h1>" > /var/www/html/index.html

Outputs:
  InstancePublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: Dirección IP pública del servidor web
