AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role para EC2

Parameters:
  StackNamePrefix:
    Type: String

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      RoleName: !Sub '${StackNamePrefix}-EC2Role'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role
      InstanceProfileName: !Sub '${StackNamePrefix}-EC2InstanceProfile'

Outputs:
  InstanceProfile:
    Value: !Ref InstanceProfile
