AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket S3 para logs o archivos

Parameters:
  nombreprefijobucket:
    Type: String
    Description: "Este es prefijo parte del nombre que le pondremos al bucket a crear"
    Default: "bucket"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${nombreprefijobucket}-${AWS::AccountId}-bucket'

Outputs:
  BucketName:
    Value: !Ref S3Bucket
